spring:
  datasource:
    db_mysql:
      url: jdbc:mysql://localhost:3306/tl?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    db_pg:
      url: jdbc:postgresql://localhost:5432/GeoCross?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: org.postgresql.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/.*xml
server:
  port: 8192
  tomcat:
    maxHttpHeaderSize: 65536
